#!/usr/bin/env python
import requests
import sys
import subprocess


print '''
		 _     _               _ _ _       _     
		| |   (_)             (_) | |     | |    
		| |__  _ ___ _ __ ___  _| | | __ _| |__  
		| '_ \| / __| '_ ` _ \| | | |/ _` | '_ \ 
		| |_) | \__ \ | | | | | | | | (_| | | | |
		|_.__/|_|___/_| |_| |_|_|_|_|\__,_|_| |_|
                                         
                  #   +++       gitbuster        +++  #
                  #       Zishan Ahamed Thandar       #
'''



filename=sys.argv[1]
with open(filename) as f:
    lines = f.readlines()

print "inputfile:", filename
outputfile = filename.split(".")[0] + "_result.txt"

def file_exists(location):
    try:
        r = requests.get(location)
        if r.status_code == 200:
        	return True
        else:
        	return False
    except:
		return False


output=""
with open(filename, "r") as ins:
    array = []
    for line in ins:
		location="http://"+line+"/.git/"
		if file_exists(location):
			result=location
			output = output + result +'\n'
			for lin in result:
			    if not lin.startswith('#'):
			        print(lin)
			        output=output+lin+'\n'
			with open(outputfile, "wb" ) as fp:
				fp.write(output)
		else:
			a=1
		output=output

  
print "argument:", sys.argv[1] 
print "outputfile:", outputfile
